const ARRAY = ["MAINGATE", "BUSINESSGATE", "ENGINEERINGGATE", "ARTGATE"];

const EAT_LOCATION = {
  MAINGATE: "MAINGATE",
  BUSINESSGATE: "BUSINESSGATE",
  ENGINEERINGGATE: "ENGINEERINGGATE",
  ARTGATE: "ARTGATE",
};

const KOREAN = {
  MAINGATE: "정문",
  BACKGATE: "후문",
  BUSINESSGATE: "상대",
  ENGINEERINGGATE: "공대",
  ARTGATE: "예대",
};

Object.freeze(EAT_LOCATION);
Object.freeze(KOREAN);

const EAT_LOCATIONS = { ...EAT_LOCATION, KOREAN, ARRAY };
Object.freeze(EAT_LOCATIONS);

export default EAT_LOCATIONS;
